version: "3.8"
services:
  mysql:
    container_name: petmily_mysql
    image: mysql:8.0.33
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - TZ=Asia/Seoul
    expose:
      - 3306
  
  petmily_api:
    depends_on:
      - mysql
    container_name: petmily_api
    platform: linux/x86_64
    build: ./api
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    ports:
      - 10115:8000
    volumes:
      - ./api:/api

volumes:
  db_data: